CREATE STREAM IF NOT EXISTS {{ .DB }}.otel_traces
(
  trace_id             string                                      CODEC(ZSTD(1)),
  span_id              string                                      CODEC(ZSTD(1)),
  parent_span_id       string                                      CODEC(ZSTD(1)),
  trace_state          string                                      CODEC(ZSTD(1)),
  span_name            low_cardinality(string)                     CODEC(ZSTD(1)),
  span_kind            low_cardinality(string)                     CODEC(ZSTD(1)),
  service_name         low_cardinality(string)                     CODEC(ZSTD(1)),
  resource_attributes  map(low_cardinality(string), string)        CODEC(ZSTD(1)),
  scope_name           string                                      CODEC(ZSTD(1)),
  scope_version        string                                      CODEC(ZSTD(1)),
  span_attributes      map(low_cardinality(string), string)        CODEC(ZSTD(1)),
  duration             uint64                                      CODEC(ZSTD(1)),
  start_time_ns        uint64                                      CODEC(ZSTD(1)),
  end_time_ns          uint64                                      CODEC(ZSTD(1)),
  status_code          low_cardinality(string)                     CODEC(ZSTD(1)),
  status_message       string                                      CODEC(ZSTD(1)),
  `events.timestamp`   array(datetime64(9))                        CODEC(ZSTD(1)),
  `events.name`        array(low_cardinality(string))              CODEC(ZSTD(1)),
  `events.attributes`  array(map(low_cardinality(string), string)) CODEC(ZSTD(1)),
  `links.trace_id`     array(string)                               CODEC(ZSTD(1)),
  `links.span_id`      array(string)                               CODEC(ZSTD(1)),
  `links.trace_state`  array(string)                               CODEC(ZSTD(1)),
  `links.attributes`   array(map(low_cardinality(string), string)) CODEC(ZSTD(1)),
  INDEX idx_trace_id       trace_id                        TYPE bloom_filter(0.001) GRANULARITY 1,
  INDEX idx_res_attr_key   map_keys(resource_attributes)   TYPE bloom_filter(0.01)  GRANULARITY 1,
  INDEX idx_res_attr_val   map_values(resource_attributes) TYPE bloom_filter(0.01)  GRANULARITY 1,
  INDEX idx_span_attr_key  map_keys(span_attributes)       TYPE bloom_filter(0.01)  GRANULARITY 1,
  INDEX idx_span_attr_val  map_values(span_attributes)     TYPE bloom_filter(0.01)  GRANULARITY 1,
  INDEX idx_duration       duration                        TYPE minmax              GRANULARITY 1
)
