INSERT INTO {{ .DB }}.alpha_catalog (alpha_name, description, equation) VALUES
  ('alpha_1',
   'Cross-sectional rank of position-of-max in signed-power-transformed conditional over last 5 buckets',
   'rank(Ts_ArgMax(SignedPower((returns < 0 ? stddev(returns, 20) : close), 2.), 5)) - 0.5'),
  ('alpha_2',
   'Negated rolling correlation (6 buckets) between rank of 2-bucket log-volume change and rank of intraday return',
   '-1 * correlation(rank(delta(log(volume), 2)), rank((close - open) / open), 6)'),
  ('alpha_3',
   'Negated rolling correlation (10 buckets) between cross-sectional ranks of open and volume',
   '-1 * correlation(rank(open), rank(volume), 10)'),
  ('alpha_4',
   'Negated time-series rank (last 9 buckets) of cross-sectional rank of low',
   '-1 * ts_rank(rank(low), 9)'),
  ('alpha_6',
   'Negated rolling correlation (10 buckets) between raw open and raw volume',
   '-1 * correlation(open, volume, 10)'),
  ('alpha_9',
   'Nested conditional on rolling min/max (5 buckets) of one-step close delta',
   'if(ts_min(delta(close,1),5)>0, delta(close,1), if(ts_max(delta(close,1),5)<0, delta(close,1), -delta(close,1)))'),
  ('alpha_12',
   'Signed one-bucket volume change times negated one-bucket close change',
   'sign(delta(volume, 1)) * (-1 * delta(close, 1))'),
  ('alpha_22',
   'Negated delta (5 buckets) of corr(high, volume, 5) times cross-sectional rank of close stddev (20 buckets)',
   '-1 * (delta(correlation(high, volume, 5), 5) * rank(stddev(close, 20)))'),
  ('alpha_41',
   'Geometric mean of high*low minus VWAP — pure intra-bar nonlinear',
   '(high * low)^0.5 - vwap'),
  ('alpha_54',
   'Pure intra-bar nonlinear OHLC ratio — no lags, no aggregation',
   '-1 * ((low - close) * open^5) / ((low - high) * close^5)')
