CREATE STREAM IF NOT EXISTS {{ .DB }}.flatten_extracted_asa_logs
(
    ingestion_time  datetime64(3),
    log_timestamp   string,
    device_name     string,
    severity        nullable(int8),
    message_id      string,
    asa_message     string,
    asa_message_parsed map(string, string),
    direction       string,
    protocol        string,
    connection_id   nullable(uint64),
    src_interface   string,
    dst_interface   string,
    src_ip          nullable(ipv4),
    dst_ip          nullable(ipv4),
    src_port        nullable(uint16),
    dst_port        nullable(uint16),
    nat_src_ip      nullable(ipv4),
    nat_dst_ip      nullable(ipv4),
    nat_src_port    nullable(uint16),
    nat_dst_port    nullable(uint16),
    faddr           nullable(ipv4),
    gaddr           nullable(ipv4),
    laddr           nullable(ipv4),
    faddr_id        nullable(uint16),
    gaddr_id        nullable(uint16),
    laddr_id        nullable(uint16),
    icmp_type       nullable(uint8),
    icmp_code       nullable(uint8),
    icmp_details    string,
    duration        string,
    bytes           nullable(uint64),
    reason          string,
    acl_name        string,
    hex_codes       string,
    tcp_flags       string,
    interface       string,
    ids_signature   nullable(uint32),
    aaa_server      nullable(ipv4),
    username        string,
    auth_reason     string,
    vpn_group       string,
    public_ip       nullable(ipv4),
    private_ip      nullable(ipv4)
)
TTL to_datetime(_tp_time) + INTERVAL {{ .Config.retention_hours }} HOUR
SETTINGS logstore_retention_bytes = '{{ .Config.logstore_retention_bytes }}', logstore_retention_ms = '{{ .Config.logstore_retention_ms }}'