CREATE VIEW IF NOT EXISTS {{ .DB }}.v_parsed_asa_logs
AS
SELECT
    *,
    multi_if(
        message_id = '302013',
        grok(asa_message,
             'Built %{DATA:direction} %{DATA:protocol} connection %{INT:connection_id} for %{DATA:src_interface}:%{IP:src_ip}/%{INT:src_port} \\(%{IP:nat_src_ip}/%{INT:nat_src_port}\\) to %{DATA:dst_interface}:%{IP:dst_ip}/%{INT:dst_port} \\(%{IP:nat_dst_ip}/%{INT:nat_dst_port}\\)'),
        message_id = '302014',
        grok(asa_message,
             'Teardown %{DATA:protocol} connection %{INT:connection_id} for %{DATA:src_interface}:%{IP:src_ip}/%{INT:src_port} to %{DATA:dst_interface}:%{IP:dst_ip}/%{INT:dst_port} duration %{DATA:duration} bytes %{INT:bytes} %{GREEDYDATA:reason}'),
        message_id = '302015',
        grok(asa_message,
             'Built %{DATA:direction} %{DATA:protocol} connection %{INT:connection_id} for %{DATA:src_interface}:%{IP:src_ip}/%{INT:src_port} \\(%{IP:nat_src_ip}/%{INT:nat_src_port}\\) to %{DATA:dst_interface}:%{IP:dst_ip}/%{INT:dst_port} \\(%{IP:nat_dst_ip}/%{INT:nat_dst_port}\\)'),
        message_id = '302016',
        grok(asa_message,
             'Teardown %{DATA:protocol} connection %{INT:connection_id} for %{DATA:src_interface}:%{IP:src_ip}/%{INT:src_port} to %{DATA:dst_interface}:%{IP:dst_ip}/%{INT:dst_port} duration %{DATA:duration} bytes %{INT:bytes}.*'),
        message_id = '302020',
        grok(asa_message,
             'Built %{DATA:direction} ICMP connection for faddr %{IP:faddr}/%{INT:faddr_id} gaddr %{IP:gaddr}/%{INT:gaddr_id} laddr %{IP:laddr}/%{INT:laddr_id}'),
        message_id = '302021',
        grok(asa_message,
             'Teardown ICMP connection for faddr %{IP:faddr}/%{INT:faddr_id} gaddr %{IP:gaddr}/%{INT:gaddr_id} laddr %{IP:laddr}/%{INT:laddr_id}( duration %{DATA:duration})?( bytes %{INT:bytes})?'),
        message_id = '305011',
        grok(asa_message,
             'Built dynamic %{DATA:protocol} translation from %{DATA:src_interface}:%{IP:src_ip}/%{INT:src_port} to %{DATA:dst_interface}:%{IP:dst_ip}/%{INT:dst_port}'),
        message_id = '305012',
        grok(asa_message,
             'Teardown dynamic %{DATA:protocol} translation from %{DATA:src_interface}:%{IP:src_ip}/%{INT:src_port} to %{DATA:dst_interface}:%{IP:dst_ip}/%{INT:dst_port} duration %{DATA:duration}'),
        message_id = '106023',
        grok(asa_message,
             'Deny %{DATA:protocol} src %{DATA:src_interface}:%{IP:src_ip}/%{INT:src_port} dst %{DATA:dst_interface}:%{IP:dst_ip}/%{INT:dst_port} by access-group "%{DATA:acl_name}" \\[%{DATA:hex_codes}\\]'),
        message_id = '106015',
        grok(asa_message,
             'Deny %{DATA:protocol} \\(no connection\\) from %{IP:src_ip}/%{INT:src_port} to %{IP:dst_ip}/%{INT:dst_port} flags %{DATA:tcp_flags} on interface %{DATA:interface}'),
        message_id = '313001',
        grok(asa_message,
             'Denied ICMP type=%{INT:icmp_type}, code=%{INT:icmp_code} from %{IP:src_ip} on interface %{DATA:interface}%{GREEDYDATA:reason}'),
        message_id = '313004',
        grok(asa_message,
             'Denied ICMP type=%{INT:icmp_type}, from laddr %{IP:src_ip} on interface %{DATA:interface} to %{IP:dst_ip}: %{GREEDYDATA:reason}'),
        message_id = '313005',
        grok(asa_message,
             'No matching connection for ICMP error message: %{GREEDYDATA:icmp_details}'),
        message_id = '400013',
        grok(asa_message,
             'IDS:%{INT:ids_signature} ICMP echo request from %{IP:src_ip} to %{IP:dst_ip} on interface %{DATA:interface}'),
        message_id = '113004',
        grok(asa_message,
             'AAA user authentication Successful: server = %{IP:aaa_server}, user = %{DATA:username}'),
        message_id = '113015',
        grok(asa_message,
             'AAA user authentication Rejected: reason = %{DATA:auth_reason}: user = %{DATA:username}, server = %{IP:aaa_server}'),
        message_id = '713172',
        grok(asa_message,
             'Group = %{DATA:vpn_group}, IP = %{IP:public_ip}, Assigned private IP = %{IP:private_ip}'),
        map_cast(['message_id'], [message_id])
    ) AS asa_message_parsed
FROM {{ .DB }}.parsed_asa_logs
