CREATE VIEW IF NOT EXISTS {{ .DB }}.v_flatten_asa_logs
AS
SELECT
    *,
    asa_message_parsed['direction'] AS direction,
    asa_message_parsed['protocol'] AS protocol,
    to_uint64_or_null(asa_message_parsed['connection_id']) AS connection_id,
    asa_message_parsed['src_interface'] AS src_interface,
    asa_message_parsed['dst_interface'] AS dst_interface,
    to_ipv4_or_null(asa_message_parsed['src_ip']) AS src_ip,
    to_ipv4_or_null(asa_message_parsed['dst_ip']) AS dst_ip,
    to_uint16_or_null(asa_message_parsed['src_port']) AS src_port,
    to_uint16_or_null(asa_message_parsed['dst_port']) AS dst_port,
    to_ipv4_or_null(asa_message_parsed['nat_src_ip']) AS nat_src_ip,
    to_ipv4_or_null(asa_message_parsed['nat_dst_ip']) AS nat_dst_ip,
    to_uint16_or_null(asa_message_parsed['nat_src_port']) AS nat_src_port,
    to_uint16_or_null(asa_message_parsed['nat_dst_port']) AS nat_dst_port,
    to_ipv4_or_null(asa_message_parsed['faddr']) AS faddr,
    to_ipv4_or_null(asa_message_parsed['gaddr']) AS gaddr,
    to_ipv4_or_null(asa_message_parsed['laddr']) AS laddr,
    to_uint16_or_null(asa_message_parsed['faddr_id']) AS faddr_id,
    to_uint16_or_null(asa_message_parsed['gaddr_id']) AS gaddr_id,
    to_uint16_or_null(asa_message_parsed['laddr_id']) AS laddr_id,
    to_uint8_or_null(asa_message_parsed['icmp_type']) AS icmp_type,
    to_uint8_or_null(asa_message_parsed['icmp_code']) AS icmp_code,
    asa_message_parsed['icmp_details'] AS icmp_details,
    asa_message_parsed['duration'] AS duration,
    to_uint64_or_null(asa_message_parsed['bytes']) AS bytes,
    asa_message_parsed['reason'] AS reason,
    asa_message_parsed['acl_name'] AS acl_name,
    asa_message_parsed['hex_codes'] AS hex_codes,
    asa_message_parsed['tcp_flags'] AS tcp_flags,
    asa_message_parsed['interface'] AS interface,
    to_uint32_or_null(asa_message_parsed['ids_signature']) AS ids_signature,
    to_ipv4_or_null(asa_message_parsed['aaa_server']) AS aaa_server,
    asa_message_parsed['username'] AS username,
    asa_message_parsed['auth_reason'] AS auth_reason,
    asa_message_parsed['vpn_group'] AS vpn_group,
    to_ipv4_or_null(asa_message_parsed['public_ip']) AS public_ip,
    to_ipv4_or_null(asa_message_parsed['private_ip']) AS private_ip
FROM {{ .DB }}.v_parsed_asa_logs
